from . import student
from . import course
from . import subject
from . import teacher
from . import calendar_courses
from . import contract
from . import career
from . import account_move
from . import semester
from . import evaluation